rong/urls.py
from django.urls import path
from .views import core, box, clanbattle, manageclan, api

app_name = 'rong'
urlpatterns = [
    path('api/add_hit/', api.kyaru_add_hit, name='api_kyaru_add_hit'),
    path('api/update_box/', api.gearbot_update_box, name='api_gearbot_update_box'),
    path('api/flight_check/', api.gearbot_flight_check, name='api_gearbot_flight_check'),
    path('api/fc_check/', api.gearbot_fc_check, name='api_gearbot_fc_check'),
    path('api/add_hits/', api.gearbot_add_hits, name='api_gearbot_add_hits'),
    path('api/get_members/', api.gearbot_get_members, name='api_gearbot_get_members'),
    path('clan/<slug:clan>/boxes/', manageclan.box_summary, name='clan_box_summary'),
    path('clan/<slug:clan>/tags/<int:tag_id>/', manageclan.edit_hit_tag, name='clan_edit_hit_tag'),
    path('clan/<slug:clan>/tags/add/', manageclan.add_hit_tag, name='clan_add_hit_tag'),
    path('clan/<slug:clan>/tags/', manageclan.list_hit_tags, name='clan_list_hit_tags'),
    path('clan/<slug:clan>/battles/<int:battle_id>/editcomp/<int:comp_id>/', manageclan.edit_comp,
         name='clan_edit_comp'),
    path('clan/<slug:clan>/battles/<int:battle_id>/addcomp/', manageclan.add_comp, name='clan_add_comp'),
    path('clan/<slug:clan>/battles/<int:battle_id>/editgroup/<int:group_id>/', manageclan.edit_hit_group,
         name='clan_edit_hit_group'),
    path('clan/<slug:clan>/battles/<int:battle_id>/addgroup/', manageclan.add_hit_group, name='clan_add_hit_group'),
    path('clan/<slug:clan>/battles/<int:battle_id>/', manageclan.edit_battle, name='clan_edit_battle'),
    path('clan/<slug:clan>/battles/add/', manageclan.add_battle, name='clan_add_battle'),
    path('clan/<slug:clan>/battles/', manageclan.list_battles, name='clan_list_battles'),
    path('clan/<slug:clan>/members/add/', manageclan.add_member, name='clan_add_member'),
    path('clan/<slug:clan>/members/<int:member_id>/', manageclan.edit_member, name='clan_edit_member'),
    path('clan/<slug:clan>/members/', manageclan.list_members, name='clan_list_members'),
    path('clanbattle/list/<slug:clan>/', clanbattle.list_battles, name='cb_list'),
    path('clanbattle/<slug:battle>/hits/<int:hit_id>/', clanbattle.edit_hit, name='cb_edit_hit'),
    path('clanbattle/<slug:battle>/hits/add/', clanbattle.add_hit, name='cb_add_hit'),
    path('clanbattle/<slug:battle>/hits/data/', clanbattle.hit_log_data, name='cb_list_hits_data'),
    path('clanbattle/<slug:battle>/hits/csv/', clanbattle.hit_log_csv, name='cb_list_hits_csv'),
    path('clanbattle/<slug:battle>/bulkpilots/', clanbattle.bulk_edit_pilots, name='cb_bulk_edit_pilots'),
    path('clanbattle/<slug:battle>/hits/', clanbattle.hit_log, name='cb_list_hits'),
    path('clanbattle/<slug:battle>/hitsactual/', clanbattle.hit_log, name='cb_list_hitsa'),
    path('clanbattle/<slug:battle>/', clanbattle.view_battle, name='cb_view'),
    path('box/', box.index, name='box_index'),
    path('box/create/', box.create_box, name='box_create'),
    path('box/<int:box_id>/', box.edit_box, name='box_edit'),
    path('box/<int:box_id>/inventory/', box.edit_inventory, name='box_inventory'),
    path('box/<int:box_id>/unit/create/', box.create_boxunit, name='box_createunit'),
    path('box/<int:box_id>/unit/<int:boxunit_id>/', box.edit_boxunit, name='box_editunit'),
    path('box/<int:box_id>/import/', box.import_box, name='box_import'),
    path('box/<int:box_id>/importli/', box.import_loadindex, name='box_import_li'),
    path('preferences/', core.preferences, name='preferences'),
    path('auth/logout/', core.logout, name='logout'),
    path('auth/login/discord/', core.discordlogin, name='discordlogin'),
    path('auth/login/discord/callback/', core.discordcallback, name='discordcallback'),
    path('', core.index, name='index'),
]

rongdjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('rong.urls'))
]

from django.conf import settings
if 'debug_toolbar' in settings.INSTALLED_APPS:
    try:
        import debug_toolbar
        urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))
    except Exception:
        pass

rong/models.py
from django.db import models

# Create your models here.

rong/models/available_unit.py
from django.db import models

class AvailableUnit(models.Model):
    member = models.ForeignKey('Member', on_delete=models.CASCADE)
    unit = models.ForeignKey('Unit', on_delete=models.CASCADE)
    power = models.PositiveIntegerField(null=True)
    level = models.PositiveIntegerField(null=True)
    star = models.PositiveIntegerField(null=True)
    rank = models.PositiveIntegerField(null=True)
    bond = models.PositiveIntegerField(null=True)
    # null = unequipped or not specified, 0-5 = refinement stars
    equip1 = models.PositiveIntegerField(null=True)
    equip2 = models.PositiveIntegerField(null=True)
    equip3 = models.PositiveIntegerField(null=True)
    equip4 = models.PositiveIntegerField(null=True)
    equip5 = models.PositiveIntegerField(null=True)
    equip6 = models.PositiveIntegerField(null=True)

rong/models/battle_arena_counter.py
from django.db import models


class BattleArenaCounter(models.Model):
    submitter = models.ForeignKey('User', null=True, on_delete=models.SET_NULL)
    from_defense = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, db_index=True)
    upvotes = models.PositiveIntegerField()
    downvotes = models.PositiveIntegerField()
    notes = models.TextField()
    attacker_team = models.ForeignKey('Team', on_delete=models.CASCADE, related_name='attacker_in')
    defender_team = models.ForeignKey('Team', on_delete=models.CASCADE, related_name='defender_in')

rong/models/bot_models.py
from django.apps import apps
from django.db import models
from django.utils.functional import cached_property


class DiscordRoleMember(models.Model):
    server_id = models.CharField(max_length=30, primary_key=True)  # hack
    role_id = models.CharField(max_length=30)
    member = models.ForeignKey('DiscordMember', db_column='member_id', on_delete=models.DO_NOTHING)

    class Meta():
        managed = False
        db_table = u'rongbot"."discord_role_members'


class DiscordServerRole(models.Model):
    server_id = models.CharField(max_length=30, primary_key=True)  # hack
    role_id = models.CharField(max_length=30)
    name = models.TextField()

    class Meta():
        managed = False
        db_table = u'rongbot"."discord_server_roles'


class DiscordMember(models.Model):
    member_id = models.CharField(max_length=30, primary_key=True)
    nickname = models.TextField()
    username = models.TextField()
    discriminator = models.IntegerField()

    class Meta():
        managed = False
        db_table = u'rongbot"."discord_members'


class UnitAlias(models.Model):
    unit_id = models.IntegerField(primary_key=True)  # hack
    name = models.TextField(db_column='unit_name')

    class Meta():
        managed = False
        db_table = u'rongbot"."unit_alias'


class Flight(models.Model):
    call_sign = models.CharField(max_length=20)
    pilot = models.ForeignKey('Pilot', db_column='pilot_id', on_delete=models.DO_NOTHING)
    clan = models.ForeignKey('Clan', db_column='clan_id', on_delete=models.DO_NOTHING, related_name='flights')
    cb = models.ForeignKey('ClanBattle', db_column='cb_id', on_delete=models.DO_NOTHING, related_name='flights')
    passenger = models.ForeignKey('ClanMember', db_column='passenger_id', null=True, on_delete=models.DO_NOTHING)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField(null=True)
    status = models.CharField(max_length=20)
    team = models.ForeignKey('Team', db_column='team_id', null=True, on_delete=models.DO_NOTHING)

    class Meta():
        managed = False
        db_table = u'rongbot"."flight'
        ordering = ['id']


class Pilot(models.Model):
    nickname = models.CharField(max_length=40)
    motto = models.TextField()
    code = models.CharField(max_length=10)
    clan = models.ForeignKey('Clan', db_column='clan_id', on_delete=models.DO_NOTHING, related_name='pilots')
    user = models.ForeignKey('User', db_column='user_id', on_delete=models.DO_NOTHING)

    @cached_property
    def clanmember(self):
        cm_model = apps.get_model('rong', 'ClanMember')
        return cm_model.objects.filter(clan_id=self.clan_id, user_id=self.user_id, active=True).first()

    class Meta():
        managed = False
        db_table = u'rongbot"."pilot'
        ordering = ['id']


class ForceQuit(models.Model):
    time = models.TimeField(db_column='time_used', primary_key=True)  # need a single (fake) PK for django
    clanmember = models.ForeignKey('ClanMember', db_column='clanmember_id', on_delete=models.DO_NOTHING,
                                   related_name='forcequits')
    cb = models.ForeignKey('ClanBattle', db_column='cb_id', on_delete=models.DO_NOTHING, related_name='forcequits')
    day = models.IntegerField(db_column='day_used')
    note = models.TextField(null=True)

    class Meta():
        managed = False
        db_table = u'rongbot"."force_quit'

rong/models/box.py
from collections import OrderedDict

from django.contrib.humanize.templatetags import humanize
from django.db import models
from django.utils import timezone, dateformat
from django.utils.functional import cached_property

from .box_unit import BoxUnit
from .box_item import BoxItem
from .redive_models import Unit, Item, StoryDetail


class Box(models.Model):
    user = models.ForeignKey('User', on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=50, null=True)
    last_update = models.DateTimeField(null=True)

    def missing_units(self):
        all_unit_ids = Unit.valid_units().values_list('id', flat=True)
        current_unit_ids = self.boxunit_set.values_list('unit_id', flat=True)
        return Unit.objects.filter(id__in=(set(all_unit_ids) - set(current_unit_ids)))

    @cached_property
    def display_name(self):
        if hasattr(self, "clanmember"):
            return "%s - %s" % (self.clanmember.clan.name, self.clanmember.ign)
        else:
            return self.name

    def unit_json(self):
        # use a consistent order for NOW
        # can be removed if wanted after sorts implemented on frontend
        units = OrderedDict()
        ordered_units = list(self.boxunit_set.all())
        ordered_units.sort(key=lambda x: x.id)
        for unit in self.boxunit_set.all():
            units[unit.id] = unit.edit_json()
        return units

    def can_edit(self, user):
        if self.user_id == user.id:
            return True
        if not hasattr(self, "clanmember"):
            return False
        if self.clanmember.user_id == user.id:
            return True
        if self.clanmember.clan_id in user.managed_clan_ids:
            return True
        return False

    def as_json(self, include_units=True):
        units = self.unit_json() if include_units else {}
        return {
            "id": self.id,
            "name": self.display_name,
            "units": units,
            "is_clan": hasattr(self, "clanmember"),
            "last_update": "N/A" if not self.last_update else humanize.naturaltime(self.last_update),
            "last_update_unixtime": 0 if not self.last_update else dateformat.format(self.last_update, 'U')
        }

    def setup_inventory_cache(self):
        if not hasattr(self, '_inventory_cache'):
            self._inventory_cache = {stock.item: stock for stock in self.inventory.all()}

    def get_item_quantity(self, item):
        self.setup_inventory_cache()
        if item not in self._inventory_cache:
            return 0
        return self._inventory_cache[item].quantity

    def set_item_quantity(self, item, quantity):
        self.setup_inventory_cache()
        if item not in self._inventory_cache:
            self._inventory_cache[item] = BoxItem(box=self, item=item, quantity=0)
        if quantity != self._inventory_cache[item].quantity:
            self._inventory_cache[item].quantity = quantity
            self._inventory_cache[item].save()

    def bulk_update_inventory(self, quantities):
        self.setup_inventory_cache()
        updates = []
        for item in quantities:
            if item not in self._inventory_cache:
                if quantities[item]:
                    self._inventory_cache[item] = BoxItem(box=self, item=item, quantity=quantities[item])
                    self._inventory_cache[item].save()
            elif self._inventory_cache[item].quantity != quantities[item]:
                self._inventory_cache[item].quantity = quantities[item]
                updates.append(self._inventory_cache[item])

        if updates:
            BoxItem.objects.bulk_update(updates, ['quantity'])

    def flag_updated(self):
        self.last_update = timezone.now()
        self.save()

    def inventory_json(self, items=None):
        if items is None:
            items = Item.inventory_items()
        return [{"id": item.id, "name": item.name, "quantity": self.get_item_quantity(item.id), "limit": item.limit_num}
                for item in items]

    def import_loadindex(self, data):
        if "unit_list" not in data and "data" in data:
            data = data["data"]
        if "unit_list" not in data:
            raise ValueError("Did not receive /load/index")
        all_units = {u.id: u for u in Unit.valid_units().prefetch_related('ranks')}
        save_units = []
        new_units = 0
        skill_levels = [
            ["ub_level", "union_burst", 0],
            ["s1_level", "main_skill", 0],
            ["s2_level", "main_skill", 1],
            ["ex_level", "ex_skill", 0],
        ]
        story_loves = {story.id: story.love_level for story in StoryDetail.objects.all()}
        for unit in data["unit_list"]:
            uid = unit["id"]
            if uid in all_units:
                unit_data = all_units[uid]
                box_unit = self.boxunit_set.filter(unit_id=uid).first()
                if not box_unit:
                    box_unit = BoxUnit(box=self, unit_id=uid, level=BoxUnit.max_level())
                    new_units += 1
                if unit["promotion_level"] > unit_data.ranks.count():
                    raise ValueError(
                        "You have %s's rank set to %d ingame, which is beyond current EN ranks." % (
                            unit_data.name, unit["p"]))
                box_unit.rank = unit["promotion_level"]
                box_unit.star = unit["unit_rarity"]
                box_unit.level = unit["unit_level"]
                for eq in range(6):
                    eq_val = unit["equip_slot"][eq]["enhancement_level"] if unit["equip_slot"][eq][
                        "is_slot"] else None
                    setattr(box_unit, 'equip%d' % (eq + 1), eq_val)
                box_unit.ue_level = None
                if unit["unique_equip_slot"] and unit["unique_equip_slot"][0]["is_slot"]:
                    box_unit.ue_level = unit["unique_equip_slot"][0]["enhancement_level"]
                for skill in skill_levels:
                    if len(unit[skill[1]]) > skill[2]:
                        setattr(box_unit, skill[0], unit[skill[1]][skill[2]]["skill_level"])
                    else:
                        setattr(box_unit, skill[0], None)
                read_bonds = [n for n in data["read_story_ids"] if n // 1000 == uid // 100]
                if read_bonds:
                    max_bond = story_loves[max(read_bonds)]
                    box_unit.bond = max_bond if max_bond else 1
                else:
                    box_unit.bond = 1
                box_unit.power = unit["power"]
                save_units.append(box_unit)
            else:
                raise ValueError("Missing unit found in your import.")

        for box_unit in save_units:
            box_unit.save()

        self.boxunit_set.exclude(id__in=[bu.id for bu in save_units]).delete()
        item_ids = [item.id for item in Item.inventory_items()]
        quantities = {item_id: 0 for item_id in item_ids}
        for item in data["item_list"]:
            if item["id"] in item_ids:
                quantities[item["id"]] = item["stock"]
        for item_id in item_ids:
            if item_id not in quantities:
                quantities[item_id] = 0
        self.bulk_update_inventory(quantities)
        self.flag_updated()

        return len(save_units), new_units

    @staticmethod
    def full_data_queryset():
        return Box.objects.select_related("clanmember", "clanmember__clan").prefetch_related(
            'boxunit_set__unit__ranks', 'boxunit_set__unit__unique_equip', 'boxunit_set__unit__rarity_6_quest',
            'inventory')

rong/models/box_item.py
from django.db import models


class BoxItem(models.Model):
    box = models.ForeignKey('Box', on_delete=models.CASCADE, related_name='inventory')
    item = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField(default=0)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['box', 'item'], name='unique box item')
        ]

rong/models/clancollection.py
from django.db import models

class ClanCollection(models.Model):
    platform_id = models.CharField(max_length=30, db_index=True)
    name = models.CharField(max_length=50)
    owner = models.ForeignKey('Member', null=True, on_delete=models.SET_NULL)

rong/models/hit_group.py
from django.db import models


class HitGroup(models.Model):
    clan_battle = models.ForeignKey('ClanBattle', on_delete=models.CASCADE, related_name='hit_groups')
    name = models.CharField(max_length=30)
    description = models.TextField(blank=True)

rong/templates/rong/clanbattle/add_hit.html
{% extends 'rong/layout.html' %}
{% load clan_battle %}
{% load humanize %}

{% load static %}
{% load bootstrap4 %}

{% block extra_js %}
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block title %}{{ battle.name }} - Add Hit{% endblock %}

{% block content %}
    <div class="row header mb-3">
        <div class="col-md-6"><h2><a href="{% url 'rong:cb_list' battle.clan.slug %}">{{ battle.clan.name }}</a> &gt; <a
                href="{% url 'rong:cb_view' battle.slug %}">{{ battle.name }}</a> &gt; Add Hit</h2></div>
        <div class="col-md-6 text-right">
            <a href="{% url 'rong:cb_list_hits' battle.slug %}" class="btn btn-primary">Hit Log</a>
            <a href="{% url 'rong:cb_view' battle.slug %}" class="btn btn-primary">Dashboard</a>
        </div>
    </div>
    <form role="form" method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' bound_css_class='' %}
        {% buttons submit='OK' reset="Cancel" %}{% endbuttons %}
    </form>
{% endblock %}

rong/templates/rong/clanbattle/edit_hit.html
{% extends 'rong/layout.html' %}
{% load clan_battle %}
{% load humanize %}

{% load static %}
{% load bootstrap4 %}

{% block extra_js %}
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block title %}{{ battle.name }} - Edit Hit{% endblock %}

{% block content %}
    <div class="row header mb-3">
        <div class="col-md-6"><h2><a href="{% url 'rong:cb_list' battle.clan.slug %}">{{ battle.clan.name }}</a> &gt; <a
                href="{% url 'rong:cb_view' battle.slug %}">{{ battle.name }}</a> &gt; Edit Hit</h2></div>
        <div class="col-md-6 text-right">
            <a href="{% url 'rong:cb_list_hits' battle.slug %}" class="btn btn-primary">Hit Log</a>
            <a href="{% url 'rong:cb_view' battle.slug %}" class="btn btn-primary">Dashboard</a>
        </div>
    </div>
    <form role="form" method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' bound_css_class='' %}
        {% buttons submit='OK' reset="Cancel" %}{% endbuttons %}
    </form>
{% endblock %}

rong/templates/rong/clanbattle/hit_log.html
{% extends 'rong/layout.html' %}
{% load unit_icons %}
{% load clan_battle %}
{% load humanize %}

{% load static %}
{% load bootstrap4 %}

{% block extra_js %}
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block title %}{{ battle.name }} - {{ battle.clan.name }}{% endblock %}

{% block content %}
    <div class="row header mb-3">
        <div class="col-md-6"><h2><a href="{% url 'rong:cb_list' battle.clan.slug %}">{{ battle.clan.name }}</a> &gt; <a
                href="{% url 'rong:cb_view' battle.slug %}">{{ battle.name }}</a> &gt; Hit Log</h2></div>
        <div class="col-md-6 text-right">
            {% can_manage request.user battle as manageable %}
            {% if manageable %}
                <button class="btn btn-primary" disabled id="bulkPilotBtn">Bulk Edit Pilots</button>
                <a href="{% url 'rong:cb_add_hit' battle.slug %}" class="btn btn-primary">Add Hit</a>
            {% endif %}
            <a href="{% url 'rong:cb_list_hits_csv' battle.slug %}" class="btn btn-primary">Download CSV</a>
            <a href="{% url 'rong:cb_view' battle.slug %}" class="btn btn-primary">Dashboard</a>
        </div>
    </div>
    <table class="table w-100 cells-middle {% if manageable %}manageable{% endif %}" id="hitLogTable"
           data-battle="{{ battle.slug }}">
        <thead>
        <tr>
            {% if manageable %}
                <th></th>
            {% endif %}
            <th>#</th>
            <th>Day</th>
            <th>Account</th>
            <th>Player</th>
            <th>Team</th>
            <th>Damage</th>
            <th>Lap</th>
            <th>Boss</th>
            <th>Remaining HP</th>
            <th>Attempts</th>
            <th>Hit Type</th>
            {% if manageable %}
                <th>Actions</th>
            {% endif %}
        </tr>
        </thead>
    </table>
    <div id="hitLogData" data-url="{% url 'rong:cb_list_hits_data' battle.slug %}" class="d-none"></div>
    <div id="filters">
        <div class="row header mb-3">
            <div class="col-md-6"><h4>Filters</h4></div>
            <div class="col-md-6 text-right">
                <button class="btn btn-primary" id="addFilter">Add Filter</button>
            </div>
        </div>
    </div>
    {% if manageable %}
        <form role="form" method="post" id="reorderForm">
            {% csrf_token %}
            <input type="hidden" name="reorderData" id="reorderData" value=""/>
        </form>
        <form role="form" method="post" id="bulkPilotForm" action="{% url 'rong:cb_bulk_edit_pilots' battle.slug %}">
            {% csrf_token %}
            <input type="hidden" name="pilotData" id="pilotData" value=""/>
        </form>
    {% endif %}
{% endblock %}

rong/templates/rong/clanbattle/list.html
{% extends 'rong/layout.html' %}
{% load unit_icons %}
{% load clan_battle %}
{% load humanize %}

{% load static %}
{% load bootstrap4 %}

{% block extra_js %}
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block title %}Clan Battles - {{ clan.name }}{% endblock %}

{% block content %}
    <h2>{{ clan.name }}'s Clan Battles</h2>
    {% if not current_cb and not past_cbs and not future_cbs %}
        <p><i>This clan has no Clan Battles defined!</i></p>
    {% endif %}
    {% if current_cb %}
        <h3>{% if current_cb.in_progress %}Current{% else %}Upcoming{% endif %} Clan Battle</h3>
        {% if current_cb.in_progress %}
            {# current #}
            <div class="jumbotron text-center position-relative">
                <div class="row align-items-center mb-3">
                    <div class="col-md-3"></div>
                    <div class="col-md-6 text-center">
                        <h1 class="display-3">{{ current_cb.name }}</h1>
                    </div>
                    <div class="col-md-3">
                        <div class="row text-left">
                            <div class="col">
                                Day {{ current_cb.current_day }}/{{ current_cb.total_days }}</div>
                        </div>
                        <div class="row text-left">
                            <div class="col">
                                {% if current_cb.next_reset < current_cb.end_time %}
                                    Reset in <b>{{ current_cb.next_reset|timeuntil }}</b>
                                {% else %}
                                    Ends in <b>{{ current_cb.end_time|timeuntil }}</b>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="{% if in_clan %}col-md-4{% else %}col-md-6{% endif %}"><h3>Current Boss</h3></div>
                    <div class="{% if in_clan %}col-md-4{% else %}col-md-6{% endif %}"><h3>Clan Progress Today</h3>
                    </div>
                    {% if in_clan %}
                        <div class="col-md-4"><h3>My Hits</h3></div>
                    {% endif %}
                </div>
                <div class="row align-items-center mb-3">
                    <div class="{% if in_clan %}col-md-4{% else %}col-md-6{% endif %}">
                        {% enemy_icon current_cb.current_boss_icon alt=current_cb.current_boss_name %}
                        <p>
                            Lap {{ current_cb.current_lap }} {{ current_cb.current_boss_name }}<br>
                            {{ current_cb.current_hp|intcomma }} HP left
                        </p>
                    </div>
                    <div class="{% if in_clan %}col-md-4{% else %}col-md-6{% endif %}">
                        <p>
                            {{ current_cb.hits_today|format_hits }} hits
                            used, {{ current_cb.hits_left_today|format_hits }} left<br/>
                            {{ current_cb.damage_dealt_today|intcomma }} damage
                            dealt, {{ current_cb.bosses_killed_today }} bosses killed
                        </p>
                        <div class="elevated-button-holder">
                            <a href="{% url 'rong:cb_list_hits' current_cb.slug %}" class="btn btn-primary">Hit Log</a>
                        </div>
                    </div>
                    {% if in_clan %}
                        <div class="col-md-4">
                            <p>
                                {% user_hits_today current_cb request.user %} hits
                                used, {% user_hits_left_today current_cb request.user %} left<br>
                                {% user_damage_today current_cb request.user %} damage dealt today
                            </p>
                        </div>
                    {% endif %}
                </div>
                <h3><a href="{% url 'rong:cb_view' current_cb.slug %}" class="stretched-link">Click to open
                    dashboard</a></h3>
            </div>
        {% else %}
            {# upcoming #}
            <div class="jumbotron text-center position-relative">
                <div class="row align-items-center mb-3">
                    <div class="col-md-3"></div>
                    <div class="col-md-6 text-center">
                        <h1 class="display-3">{{ current_cb.name }}</h1>
                    </div>
                    <div class="col-md-3">
                        <div class="row">
                            <div class="col-md-5">Starts in</div>
                            <div class="col-md-7">{{ current_cb.start_time|timeuntil }}</div>
                        </div>
                        <div class="row">
                            <div class="col-md-5">Ends in</div>
                            <div class="col-md-7">{{ current_cb.end_time|timeuntil }}</div>
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    {% for boss in current_cb.boss_list %}
                        <div class="col-boss">
                            {% enemy_icon boss.icon alt=boss.name %}<br/>
                            {{ boss.name }}
                        </div>
                    {% endfor %}
                </div>
                <h3><a href="{% url 'rong:cb_view' current_cb.slug %}" class="stretched-link">Click to open
                    dashboard</a></h3>
            </div>
        {% endif %}
    {% endif %}
    {% if future_cbs %}
        <h3>Future Clan Battles</h3>
        <table class="table w-100">
            {% for cb in future_cbs %}
                <tr>
                    <td class="align-middle w-15">{{ cb.name }}</td>
                    <td class="align-middle w-55">
                        <div class="row">
                            {% for boss in cb.boss_list %}
                                <div class="col-boss">
                                    {% enemy_icon boss.icon alt=boss.name %}
                                </div>
                            {% endfor %}
                        </div>
                    </td>
                    <td class="align-middle w-15">
                        {% if cb.start_time %}
                            {{ cb.start_time|date:"Y/m/d" }}-{{ cb.end_time|date:"Y/m/d" }}
                        {% else %}
                            <i>No dates yet</i>
                        {% endif %}
                    </td>
                    <td class="align-middle w-15"><a class="btn btn-primary" href="{% url 'rong:cb_view' cb.slug %}">Dashboard</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}
    {% if past_cbs %}
        <h3>Past Clan Battles</h3>
        <table class="table w-100">
            {% for cb in past_cbs %}
                <tr>
                    <td class="align-middle w-15">{{ cb.name }}</td>
                    <td class="align-middle w-55">
                        <div class="row">
                            {% for boss in cb.boss_list %}
                                <div class="col-boss">
                                    {% enemy_icon boss.icon alt=boss.name %}
                                </div>
                            {% endfor %}
                        </div>
                    </td>
                    <td class="align-middle w-15">{{ cb.start_time|date:"Y/m/d" }}-{{ cb.end_time|date:"Y/m/d" }}</td>
                    <td class="align-middle w-15"><a class="btn btn-primary" href="{% url 'rong:cb_view' cb.slug %}">Summary</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}
{% endblock %}