rong/urls.py
from django.urls import path
from .views import core, box, clanbattle, manageclan, api

app_name = 'rong'
urlpatterns = [
    path('api/add_hit/', api.kyaru_add_hit, name='api_kyaru_add_hit'),
    path('api/update_box/', api.gearbot_update_box, name='api_gearbot_update_box'),
    path('api/flight_check/', api.gearbot_flight_check, name='api_gearbot_flight_check'),
    path('api/fc_check/', api.gearbot_fc_check, name='api_gearbot_fc_check'),
    path('api/add_hits/', api.gearbot_add_hits, name='api_gearbot_add_hits'),
    path('api/get_members/', api.gearbot_get_members, name='api_gearbot_get_members'),
    path('clan/<slug:clan>/boxes/', manageclan.box_summary, name='clan_box_summary'),
    path('clan/<slug:clan>/tags/<int:tag_id>/', manageclan.edit_hit_tag, name='clan_edit_hit_tag'),
    path('clan/<slug:clan>/tags/add/', manageclan.add_hit_tag, name='clan_add_hit_tag'),
    path('clan/<slug:clan>/tags/', manageclan.list_hit_tags, name='clan_list_hit_tags'),
    path('clan/<slug:clan>/battles/<int:battle_id>/editcomp/<int:comp_id>/', manageclan.edit_comp,
         name='clan_edit_comp'),
    path('clan/<slug:clan>/battles/<int:battle_id>/addcomp/', manageclan.add_comp, name='clan_add_comp'),
    path('clan/<slug:clan>/battles/<int:battle_id>/editgroup/<int:group_id>/', manageclan.edit_hit_group,
         name='clan_edit_hit_group'),
    path('clan/<slug:clan>/battles/<int:battle_id>/addgroup/', manageclan.add_hit_group, name='clan_add_hit_group'),
    path('clan/<slug:clan>/battles/<int:battle_id>/', manageclan.edit_battle, name='clan_edit_battle'),
    path('clan/<slug:clan>/battles/add/', manageclan.add_battle, name='clan_add_battle'),
    path('clan/<slug:clan>/battles/', manageclan.list_battles, name='clan_list_battles'),
    path('clan/<slug:clan>/members/add/', manageclan.add_member, name='clan_add_member'),
    path('clan/<slug:clan>/members/<int:member_id>/', manageclan.edit_member, name='clan_edit_member'),
    path('clan/<slug:clan>/members/', manageclan.list_members, name='clan_list_members'),
    path('clanbattle/list/<slug:clan>/', clanbattle.list_battles, name='cb_list'),
    path('clanbattle/<slug:battle>/hits/<int:hit_id>/', clanbattle.edit_hit, name='cb_edit_hit'),
    path('clanbattle/<slug:battle>/hits/add/', clanbattle.add_hit, name='cb_add_hit'),
    path('clanbattle/<slug:battle>/hits/data/', clanbattle.hit_log_data, name='cb_list_hits_data'),
    path('clanbattle/<slug:battle>/hits/csv/', clanbattle.hit_log_csv, name='cb_list_hits_csv'),
    path('clanbattle/<slug:battle>/bulkpilots/', clanbattle.bulk_edit_pilots, name='cb_bulk_edit_pilots'),
    path('clanbattle/<slug:battle>/hits/', clanbattle.hit_log, name='cb_list_hits'),
    path('clanbattle/<slug:battle>/hitsactual/', clanbattle.hit_log, name='cb_list_hitsa'),
    path('clanbattle/<slug:battle>/', clanbattle.view_battle, name='cb_view'),
    path('box/', box.index, name='box_index'),
    path('box/create/', box.create_box, name='box_create'),
    path('box/<int:box_id>/', box.edit_box, name='box_edit'),
    path('box/<int:box_id>/inventory/', box.edit_inventory, name='box_inventory'),
    path('box/<int:box_id>/unit/create/', box.create_boxunit, name='box_createunit'),
    path('box/<int:box_id>/unit/<int:boxunit_id>/', box.edit_boxunit, name='box_editunit'),
    path('box/<int:box_id>/import/', box.import_box, name='box_import'),
    path('box/<int:box_id>/importli/', box.import_loadindex, name='box_import_li'),
    path('preferences/', core.preferences, name='preferences'),
    path('auth/logout/', core.logout, name='logout'),
    path('auth/login/discord/', core.discordlogin, name='discordlogin'),
    path('auth/login/discord/callback/', core.discordcallback, name='discordcallback'),
    path('', core.index, name='index'),
]

rongdjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('rong.urls'))
]

from django.conf import settings
if 'debug_toolbar' in settings.INSTALLED_APPS:
    try:
        import debug_toolbar
        urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))
    except Exception:
        pass

rong/models.py
from django.db import models

# Create your models here.

rong/models/available_unit.py
from django.db import models

class AvailableUnit(models.Model):
    member = models.ForeignKey('Member', on_delete=models.CASCADE)
    unit = models.ForeignKey('Unit', on_delete=models.CASCADE)
    power = models.PositiveIntegerField(null=True)
    level = models.PositiveIntegerField(null=True)
    star = models.PositiveIntegerField(null=True)
    rank = models.PositiveIntegerField(null=True)
    bond = models.PositiveIntegerField(null=True)
    # null = unequipped or not specified, 0-5 = refinement stars
    equip1 = models.PositiveIntegerField(null=True)
    equip2 = models.PositiveIntegerField(null=True)
    equip3 = models.PositiveIntegerField(null=True)
    equip4 = models.PositiveIntegerField(null=True)
    equip5 = models.PositiveIntegerField(null=True)
    equip6 = models.PositiveIntegerField(null=True)

rong/models/battle_arena_counter.py
from django.db import models


class BattleArenaCounter(models.Model):
    submitter = models.ForeignKey('User', null=True, on_delete=models.SET_NULL)
    from_defense = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, db_index=True)
    upvotes = models.PositiveIntegerField()
    downvotes = models.PositiveIntegerField()
    notes = models.TextField()
    attacker_team = models.ForeignKey('Team', on_delete=models.CASCADE, related_name='attacker_in')
    defender_team = models.ForeignKey('Team', on_delete=models.CASCADE, related_name='defender_in')

rong/models/bot_models.py
from django.apps import apps
from django.db import models
from django.utils.functional import cached_property


class DiscordRoleMember(models.Model):
    server_id = models.CharField(max_length=30, primary_key=True)  # hack
    role_id = models.CharField(max_length=30)
    member = models.ForeignKey('DiscordMember', db_column='member_id', on_delete=models.DO_NOTHING)

    class Meta():
        managed = False
        db_table = u'rongbot"."discord_role_members'


class DiscordServerRole(models.Model):
    server_id = models.CharField(max_length=30, primary_key=True)  # hack
    role_id = models.CharField(max_length=30)
    name = models.TextField()

    class Meta():
        managed = False
        db_table = u'rongbot"."discord_server_roles'


class DiscordMember(models.Model):
    member_id = models.CharField(max_length=30, primary_key=True)
    nickname = models.TextField()
    username = models.TextField()
    discriminator = models.IntegerField()

    class Meta():
        managed = False
        db_table = u'rongbot"."discord_members'


class UnitAlias(models.Model):
    unit_id = models.IntegerField(primary_key=True)  # hack
    name = models.TextField(db_column='unit_name')

    class Meta():
        managed = False
        db_table = u'rongbot"."unit_alias'


class Flight(models.Model):
    call_sign = models.CharField(max_length=20)
    pilot = models.ForeignKey('Pilot', db_column='pilot_id', on_delete=models.DO_NOTHING)
    clan = models.ForeignKey('Clan', db_column='clan_id', on_delete=models.DO_NOTHING, related_name='flights')
    cb = models.ForeignKey('ClanBattle', db_column='cb_id', on_delete=models.DO_NOTHING, related_name='flights')
    passenger = models.ForeignKey('ClanMember', db_column='passenger_id', null=True, on_delete=models.DO_NOTHING)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField(null=True)
    status = models.CharField(max_length=20)
    team = models.ForeignKey('Team', db_column='team_id', null=True, on_delete=models.DO_NOTHING)

    class Meta():
        managed = False
        db_table = u'rongbot"."flight'
        ordering = ['id']


class Pilot(models.Model):
    nickname = models.CharField(max_length=40)
    motto = models.TextField()
    code = models.CharField(max_length=10)
    clan = models.ForeignKey('Clan', db_column='clan_id', on_delete=models.DO_NOTHING, related_name='pilots')
    user = models.ForeignKey('User', db_column='user_id', on_delete=models.DO_NOTHING)

    @cached_property
    def clanmember(self):
        cm_model = apps.get_model('rong', 'ClanMember')
        return cm_model.objects.filter(clan_id=self.clan_id, user_id=self.user_id, active=True).first()

    class Meta():
        managed = False
        db_table = u'rongbot"."pilot'
        ordering = ['id']


class ForceQuit(models.Model):
    time = models.TimeField(db_column='time_used', primary_key=True)  # need a single (fake) PK for django
    clanmember = models.ForeignKey('ClanMember', db_column='clanmember_id', on_delete=models.DO_NOTHING,
                                   related_name='forcequits')
    cb = models.ForeignKey('ClanBattle', db_column='cb_id', on_delete=models.DO_NOTHING, related_name='forcequits')
    day = models.IntegerField(db_column='day_used')
    note = models.TextField(null=True)

    class Meta():
        managed = False
        db_table = u'rongbot"."force_quit'

rong/models/box.py
from collections import OrderedDict

from django.contrib.humanize.templatetags import humanize
from django.db import models
from django.utils import timezone, dateformat
from django.utils.functional import cached_property

from .box_unit import BoxUnit
from .box_item import BoxItem
from .redive_models import Unit, Item, StoryDetail


class Box(models.Model):
    user = models.ForeignKey('User', on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=50, null=True)
    last_update = models.DateTimeField(null=True)

    def missing_units(self):
        all_unit_ids = Unit.valid_units().values_list('id', flat=True)
        current_unit_ids = self.boxunit_set.values_list('unit_id', flat=True)
        return Unit.objects.filter(id__in=(set(all_unit_ids) - set(current_unit_ids)))

    @cached_property
    def display_name(self):
        if hasattr(self, "clanmember"):
            return "%s - %s" % (self.clanmember.clan.name, self.clanmember.ign)
        else:
            return self.name

    def unit_json(self):
        # use a consistent order for NOW
        # can be removed if wanted after sorts implemented on frontend
        units = OrderedDict()
        ordered_units = list(self.boxunit_set.all())
        ordered_units.sort(key=lambda x: x.id)
        for unit in self.boxunit_set.all():
            units[unit.id] = unit.edit_json()
        return units

    def can_edit(self, user):
        if self.user_id == user.id:
            return True
        if not hasattr(self, "clanmember"):
            return False
        if self.clanmember.user_id == user.id:
            return True
        if self.clanmember.clan_id in user.managed_clan_ids:
            return True
        return False

    def as_json(self, include_units=True):
        units = self.unit_json() if include_units else {}
        return {
            "id": self.id,
            "name": self.display_name,
            "units": units,
            "is_clan": hasattr(self, "clanmember"),
            "last_update": "N/A" if not self.last_update else humanize.naturaltime(self.last_update),
            "last_update_unixtime": 0 if not self.last_update else dateformat.format(self.last_update, 'U')
        }

    def setup_inventory_cache(self):
        if not hasattr(self, '_inventory_cache'):
            self._inventory_cache = {stock.item: stock for stock in self.inventory.all()}

    def get_item_quantity(self, item):
        self.setup_inventory_cache()
        if item not in self._inventory_cache:
            return 0
        return self._inventory_cache[item].quantity

    def set_item_quantity(self, item, quantity):
        self.setup_inventory_cache()
        if item not in self._inventory_cache:
            self._inventory_cache[item] = BoxItem(box=self, item=item, quantity=0)
        if quantity != self._inventory_cache[item].quantity:
            self._inventory_cache[item].quantity = quantity
            self._inventory_cache[item].save()

    def bulk_update_inventory(self, quantities):
        self.setup_inventory_cache()
        updates = []
        for item in quantities:
            if item not in self._inventory_cache:
                if quantities[item]:
                    self._inventory_cache[item] = BoxItem(box=self, item=item, quantity=quantities[item])
                    self._inventory_cache[item].save()
            elif self._inventory_cache[item].quantity != quantities[item]:
                self._inventory_cache[item].quantity = quantities[item]
                updates.append(self._inventory_cache[item])

        if updates:
            BoxItem.objects.bulk_update(updates, ['quantity'])

    def flag_updated(self):
        self.last_update = timezone.now()
        self.save()

    def inventory_json(self, items=None):
        if items is None:
            items = Item.inventory_items()
        return [{"id": item.id, "name": item.name, "quantity": self.get_item_quantity(item.id), "limit": item.limit_num}
                for item in items]

    def import_loadindex(self, data):
        if "unit_list" not in data and "data" in data:
            data = data["data"]
        if "unit_list" not in data:
            raise ValueError("Did not receive /load/index")
        all_units = {u.id: u for u in Unit.valid_units().prefetch_related('ranks')}
        save_units = []
        new_units = 0
        skill_levels = [
            ["ub_level", "union_burst", 0],
            ["s1_level", "main_skill", 0],
            ["s2_level", "main_skill", 1],
            ["ex_level", "ex_skill", 0],
        ]
        story_loves = {story.id: story.love_level for story in StoryDetail.objects.all()}
        for unit in data["unit_list"]:
            uid = unit["id"]
            if uid in all_units:
                unit_data = all_units[uid]
                box_unit = self.boxunit_set.filter(unit_id=uid).first()
                if not box_unit:
                    box_unit = BoxUnit(box=self, unit_id=uid, level=BoxUnit.max_level())
                    new_units += 1
                if unit["promotion_level"] > unit_data.ranks.count():
                    raise ValueError(
                        "You have %s's rank set to %d ingame, which is beyond current EN ranks." % (
                            unit_data.name, unit["p"]))
                box_unit.rank = unit["promotion_level"]
                box_unit.star = unit["unit_rarity"]
                box_unit.level = unit["unit_level"]
                for eq in range(6):
                    eq_val = unit["equip_slot"][eq]["enhancement_level"] if unit["equip_slot"][eq][
                        "is_slot"] else None
                    setattr(box_unit, 'equip%d' % (eq + 1), eq_val)
                box_unit.ue_level = None
                if unit["unique_equip_slot"] and unit["unique_equip_slot"][0]["is_slot"]:
                    box_unit.ue_level = unit["unique_equip_slot"][0]["enhancement_level"]
                for skill in skill_levels:
                    if len(unit[skill[1]]) > skill[2]:
                        setattr(box_unit, skill[0], unit[skill[1]][skill[2]]["skill_level"])
                    else:
                        setattr(box_unit, skill[0], None)
                read_bonds = [n for n in data["read_story_ids"] if n // 1000 == uid // 100]
                if read_bonds:
                    max_bond = story_loves[max(read_bonds)]
                    box_unit.bond = max_bond if max_bond else 1
                else:
                    box_unit.bond = 1
                box_unit.power = unit["power"]
                save_units.append(box_unit)
            else:
                raise ValueError("Missing unit found in your import.")

        for box_unit in save_units:
            box_unit.save()

        self.boxunit_set.exclude(id__in=[bu.id for bu in save_units]).delete()
        item_ids = [item.id for item in Item.inventory_items()]
        quantities = {item_id: 0 for item_id in item_ids}
        for item in data["item_list"]:
            if item["id"] in item_ids:
                quantities[item["id"]] = item["stock"]
        for item_id in item_ids:
            if item_id not in quantities:
                quantities[item_id] = 0
        self.bulk_update_inventory(quantities)
        self.flag_updated()

        return len(save_units), new_units

    @staticmethod
    def full_data_queryset():
        return Box.objects.select_related("clanmember", "clanmember__clan").prefetch_related(
            'boxunit_set__unit__ranks', 'boxunit_set__unit__unique_equip', 'boxunit_set__unit__rarity_6_quest',
            'inventory')

rong/models/box_item.py
from django.db import models


class BoxItem(models.Model):
    box = models.ForeignKey('Box', on_delete=models.CASCADE, related_name='inventory')
    item = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField(default=0)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['box', 'item'], name='unique box item')
        ]

rong/models/clancollection.py
from django.db import models

class ClanCollection(models.Model):
    platform_id = models.CharField(max_length=30, db_index=True)
    name = models.CharField(max_length=50)
    owner = models.ForeignKey('Member', null=True, on_delete=models.SET_NULL)

rong/models/hit_group.py
from django.db import models


class HitGroup(models.Model):
    clan_battle = models.ForeignKey('ClanBattle', on_delete=models.CASCADE, related_name='hit_groups')
    name = models.CharField(max_length=30)
    description = models.TextField(blank=True)

rong/templates/rong/index.html
{% extends 'rong/layout.html' %}

{% load unit_icons %}
{% load static %}
{% load bootstrap4 %}

{% block title %}Rong - PCDR Helper{% endblock %}

{% block content %}
    <h2>Home</h2>
    {% if user.is_authenticated %}
        <p>Welcome, {{ user.name }}.</p>
        <h3>This is a good team</h3>
        <p>
            {% box_icon '104701' 2 4 %}
            {% unit_icon '103831' border='gold' stars=5 %}
            {% unit_icon '102831' border='gold' stars=4 %}
            {% unit_icon '104331' border='gold' stars=5 %}
            {% unit_icon '101731' border='gold' stars=5 %}
            {% unit_icon '104731' border='gold' stars=4 %}
        </p>
    {% else %}
        <a href='{% url 'rong:discordlogin' %}'>Login</a>
    {% endif %}
{% endblock %}

rong/templates/rong/layout.html
<!DOCTYPE html>
{% load bootstrap4 %}
{% load unit_icons %}
{% load render_bundle from webpack_loader %}
<html lang="en-US">

<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Page title -->
    <title>Rong - {% block title %}{% endblock %}</title>

    {% load static %}
    <link rel='shortcut icon' type='image/x-icon' href='{% static "rong/favicon.ico" %}'/>
    {% render_bundle 'app' 'css' %}
    {% block extra_css %}{% endblock %}

    <!-- Bootstrap JavaScript if it is in head -->

</head>

<body>
<nav class="navbar navbar-dark bg-dark fixed-top navbar-expand-lg">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'rong:index' %}">Rong</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="nav navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'rong:box_index' %}">My Box</a>
                    </li>

                    {# Clan Battle #}
                    {% with user.clans.all as clans %}
                        {% if clans|length == 1 %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'rong:cb_list' clans.first.slug %}">Clan Battle</a>
                            </li>
                        {% elif clans|length > 1 %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#">Clan Battle</a>
                                <ul class="dropdown-menu">
                                    {% for clan in clans %}
                                        <li><a class="dropdown-item"
                                               href="{% url 'rong:cb_list' clan.slug %}">{{ clan.name }}</a></li>
                                    {% endfor %}
                                </ul>
                            </li>
                        {% endif %}
                    {% endwith %}

                    {# Clan Management #}
                    {% if user.listed_clans|length %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#">Manage Clans</a>
                            <ul class="dropdown-menu">
                                {% if user.listed_clans|length < 3 %}
                                    {% for clan in user.listed_clans %}
                                        {% if not forloop.first %}
                                            <li class="dropdown-divider"></li>
                                        {% endif %}
                                        <li class="dropdown-header">{{ clan.name }}</li>
                                        {% include "./includes/clan_management_menu_items.html" %}
                                    {% endfor %}
                                {% else %}
                                    {% for clan in user.listed_clans %}
                                        <li class="dropdown">
                                            <a class="dropdown-item dropdown-toggle" href="#">{{ clan.name }}</a>
                                            <ul class="dropdown-menu">
                                                {% include "./includes/clan_management_menu_items.html" %}
                                            </ul>
                                        </li>
                                    {% endfor %}
                                {% endif %}
                            </ul>
                        </li>
                    {% endif %}
                {% endif %}
            </ul>
            <ul class="navbar-nav align-items-center">
                {% if user.is_authenticated %}
                    <!-- display pic here -->
                    <li class="nav-item">
                        {% unit_icon user.display_pic pfp=True %}
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="userSettingsDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                            {{ user.name }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="userSettingsDropdown">
                            <a class="dropdown-item" href="{% url 'rong:preferences' %}">Preferences</a>
                            <a class="dropdown-item" href="{% url 'rong:logout' %}">Logout</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'rong:discordlogin' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% if request.resolver_match.url_name == "cb_list_hits" %}
    <div class="container page__{{ request.resolver_match.url_name }}" id="mainContent">
{% else %}
    <div class="container-fluid page__{{ request.resolver_match.url_name }}" id="mainContent">
{% endif %}

    {% bootstrap_messages %}

    {% block content %}{% endblock %}
</div>

<hr/>

<div class="container-fluid">
    Princess Connect Re;Dive &copy; Cygames &amp; licensed by Crunchyroll Games.<br/>
    The creator of this website is not affiliated with either of these entities.
</div>

<div class="loading-overlay transition-delay"></div>
<div class="loading-spanner transition-delay">
    <div class="loader"></div>
    <p>Loading...</p>
</div>

<!-- Bootstrap JavaScript if it is in body -->

{% block extra_script %}{% endblock %}

{% load unit_nicknames %}
{% nicknames %}

</body>

{% render_bundle 'app' 'js' %}

</html>

rong/templates/rong/preferences.html
{% extends 'rong/layout.html' %}

{% load unit_icons %}
{% load static %}
{% load bootstrap4 %}

{% block title %}Preferences{% endblock %}

{% block content %}
    <h2>User Preferences</h2>
    <form role="form" method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' bound_css_class='' %}
        {% buttons submit='OK' reset="Cancel" %}{% endbuttons %}
    </form>
{% endblock %}

rong/templates/rong/test_unitselect.html
{% extends 'rong/layout.html' %}

{% load static %}
{% load bootstrap4 %}

{% block extra_js %}
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block title %}Unit Selector Testing Grounds{% endblock %}

{% block content %}
    <form role="form" method="post">
        <div class="form-group row">
            <label class="col-md-3 col-form-label" for="unitTest">Test unit</label>
            <div class="col-md-9">
                <select name="unit_test" id="unitTest" class="form-control unit-selector">
                    <option selected value></option>
                    {% for unit in units %}
                        <option value="{{ unit.id }}">{{ unit.name }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-md-1 col-form-label" for="unitTestD">Unit 1</label>
            <div class="col-md-3">
                <select name="unit_test3" id="unitTestD" class="form-control unit-selector">
                    <option selected value></option>
                    {% for unit in units %}
                        <option value="{{ unit.id }}">{{ unit.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <label class="col-md-1 col-form-label" for="unitDamage">Damage</label>
            <div class="col-md-2">
                <input type="number" name="unit_damage" id="unitDamage" class="form-control"/>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-md-3 col-form-label" for="unitTest2">Test units multi</label>
            <div class="col-md-9">
                <select name="unit_test2" id="unitTest2" class="form-control unit-multi-selector" multiple>
                    {% for unit in units %}
                        <option value="{{ unit.id }}">{{ unit.name }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
    </form>
{% endblock %}